### ISSUE TITLE
[RFE] prototype usage of vault sidecar agent

### ISSUE THREAD

**Issue by rovandep** [ondat/trousseau#31]
Is it linked to a user story? (use the "#" to tag the user story)
No

What do we want to build?
Use the concept of the sidecar agent to handle auth towards vault instead of recovery a user generated token that could be used for potential privilege access to vault 

Why do we want to build it?
Improve usability and security

How do we want to design it?
Similar to https://www.hashicorp.com/blog/dynamic-database-credentials-with-vault-and-kubernetes

**Comment by rovandep** [comment]
working on branch issue-31

**Comment by rovandep** [comment]
Dear Team,

Please find my conclusion after running a series of prototypes around the Vault Agend/Sidecar integration. 

The current code base is using the local internal/config pkg to break down a manually created YAML configuration file to feed a minimal set of parameters like the vault address, token, and transit key name to Trousseau in order to encrypt/decrypt payloads using the Vault Transit engine. 

Based on the [Vault Agent with with Kubernetes](https://learn.hashicorp.com/tutorials/vault/agent-kubernetes) documentation leading to: 
![vault k8s agent auto auth](https://learn.hashicorp.com/img/vault/diagram-vault_agent-kubernetes-workflow.png)   

I propose as a first iteration of the Vault Agent/Sidecar a "almost zero code" change by:

- [ ] leveraging the templating method to inject a similar YAML configuration file as the one generated manually within the container
- [ ] introduce a k8s configuration 
- [ ] introduce a ConfigMap 
- [ ] change the DaemonSet spec:containers:args:"--config-file-path=/opt/vault-kms/config.yaml" to a folder of our choice within the vault-kms-provider container (which makes it ephemeral)
- [ ] introduce a code change to void any options for a user to customize spec:containers:args:"--config-file-path=/opt/vault-kms/config.yaml"

The work is mainly linked to documentation with some minor changes on the k8s configuration  set. 

I can forecast as a second iteration a series of optmisations to improve the user experience like having all the above within a Helm chart and/or an Operator (I know I know :)  

@vfiftyfive @hubvu - Thank you for commenting - if you thumbs up this proposal, I will push my prototype within branch issue-31 so that you could give it a spin.

**Comment by cannisondat** [comment]
Please review and update the documentation we currently have as part of this task - thank you

**Comment by cannischan** [comment]
@mhmxs could you please have a look at this from the design perspective?

**Comment by rovandep** [comment]
# Current design 
The current code base depends on a YAML configuration file deployed on each control plane node requiring the following minimum details:

```YAML
---
provider: vault
vault:
  keynames:
  - <transit key name> 
  address: <http[s] vault address:8200>
  token: <auth token> 
```

where:
- ```<transit key name>``` is the name of the created transit key dedicated to Trousseau
- ```<http[s] vault address:8200>``` is the HashiCorp Vault API URL
- ```<auth token>``` is the authentication token with access to the transit engine

Trousseau container mount the local node directory ```/opt/vault-kms``` to access the above configuration and start its socket that will be will created within the same directory.  
This allows the [Kubernetes API manager](https://kubernetes.io/docs/tasks/administer-cluster/kms-provider/) to access the socket to send secret transaction towards Trousseau. 

Pro:
- easy to setup especially in demo environment using the root token 
Con:
- expose the token and transit name key use for in-flight encryption
- no concept of trust between Kubernetes and Vault using RBAC model 
- reduce flexibility in case of segration of duties if multiple Vault servers

# Proposed design
To reduce potential regressions at the code base level, the following approach allows to proof the Vault Agent approach with zero code changes by using 2 Vault has 2 features:
- Authentication for Kubernetes; a JWT token based authentication using a Kubernetes ServiceAccount 
- Vault Agent; a initContainer with the Vault tooling to inject secret to an application

These 2 features set up a trust between a Pod within a defined NameSpace and Vault to retrieve secrets and inject them in multiple different format with the Pod. 

The configuration workflow is as follow:
- create a Kubernetes ServiceAccount within the kube-system namespace (where Trousseau lives)
- create a Vault policy for the app Trousseau to read and list data 
- create a secret using kv pairs to include the transit key name, the API Vault address and auth token
- enable and configure the Kubernetes authentication 
- create a Trousseau role linked to ServiceAccount and Kubernetes authentication 
- create a ConfigMap templating the YAML configuration file to be injected with Trousseau container(s)
- use the modified DaemonSet definition 
- enjoy!

# Technical bits for PoC
Requirements:
- a working Kubernetes cluster with 1 control plane node and 1 worker node to verify proper deployment with properties like affinity, ...
- a Vault instance, Community or Enterprise edition, deployable within a Kubernetes (not the same one as Trousseau) or outside of Kubernetes 
- assuming ```kubectl``` and ```vault``` CLI tooling is deployed on a control plane node 
- assuming my API Vault address is tdevhvc-01.trousseau.io
Steps:
* start a Vault instance
```
vault server -dev -dev-root-token-id root -dev-listen-address 0.0.0.0:8200
``` 
and check access from the Kubernetes control plane node
```
export VAULT_ADDR=http://tdevhvc-01.trousseau.io:8200
vault status 
```
will give:
```
Key             Value
---             -----
Seal Type       shamir
Initialized     true
Sealed          false
Total Shares    1
Threshold       1
Version         1.9.3
Storage Type    inmem
Cluster Name    vault-cluster-caa9ea4c
Cluster ID      701cb42f-adfc-52aa-2a5a-53776fed0138
HA Enabled      false
```

* create ServiceAccount using the following manifest and commands:
```
kubectl -n kube-system create serviceaccount vault-auth
```
vault-auth-serviceaccount.yaml:
```YAML
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
   name: role-tokenreview-binding
   namespace: kube-system
roleRef:
   apiGroup: rbac.authorization.k8s.io
   kind: ClusterRole
   name: system:auth-delegator
subjects:
- kind: ServiceAccount
  name: vault-auth
  namespace: kube-system
``` 
```
kubectl apply -f vault-auth-serviceaccount.yaml
```

* enable and configure Kubernetes auth in Vault
```
vault policy write trousseau-kv-ro - <<EOF
path "secret/data/trousseau/*" {
    capabilities = ["read", "list"]
}
EOF
```
```
vault kv put /secret/trousseau/config transitkeyname=trousseau-kms-vault \
vaultaddress=http://tdevhvc-01.trousseau.io:8200 vaulttoken=s.tgp6WW9klulUKmpg0TLlEuA5 \
 ttl=30s
```
```
export VAULT_SA_NAME=$(kubectl -n kube-system get sa vault-auth \
    --output jsonpath="{.secrets[*]['name']}")
```
```
export SA_JWT_TOKEN=$(kubectl -n kube-system get secret $VAULT_SA_NAME \
    --output 'go-template={{ .data.token }}' | base64 --decode)
```
```
export SA_CA_CRT=$(kubectl -n kube-system config view --raw --minify --flatten \
    --output 'jsonpath={.clusters[].cluster.certificate-authority-data}' | base64 --decode)
```
```
export K8S_HOST=$(kubectl config view --raw --minify --flatten \
    --output 'jsonpath={.clusters[].cluster.server}')
```
**NOTE**: the ```K8S_HOST``` might return "https://127.0.0.1:6443" resulting to a failure when Vault will dialback to the Kubernetes cluster to do an API call for ```tokenreviews```.
If this is the case, export manually the external IP/FQDN (like ```export K8S_HOST=192.168.1.110``` giving access to your clusters from an external resource (like the Vault server). 

```
vault auth enable kubernetes
vault write auth/kubernetes/config \
        token_reviewer_jwt="$SA_JWT_TOKEN" \
        kubernetes_host="$K8S_HOST" \
        kubernetes_ca_cert="$SA_CA_CRT" \
        issuer="https://kubernetes.default.svc.cluster.local"
vault write auth/kubernetes/role/trousseau \
        bound_service_account_names=vault-auth \
        bound_service_account_namespaces=kube-system \
        policies=trousseau-kv-ro \
        ttl=24h
```

* Create a ConfigMap 
vault-configmap.yaml:
```YAML
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: trousseau-vault-agent-config
  namespace: kube-system
data:
  vault-agent-config.hcl: |
    exit_after_auth = true
    pid_file = "/home/vault/pidfile"
    auto_auth {
        method "kubernetes" {
            mount_path = "auth/kubernetes"
            config = {
                role = "trousseau"
            }
        }
        sink "file" {
            config = {
                path = "/home/vault/.vault-token"
            }
        }
    }

    template {
    destination = "/etc/secrets/config.yaml"
    contents = <<EOT
    {{- with secret "secret/data/trousseau/config" }}
    --- 
    provider: vault
    vault:
      keynames:
      - {{ .Data.data.transitkeyname }} 
      address: {{ .Data.data.vaultaddress }} 
      token: {{ .Data.data.vaulttoken }} 
    {{ end }} 
    EOT
    }
```
```
kubectl apply -f vault-configmap.yaml
```

* Deploy Trousseau custom DaemonSet:
```YAML
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: vault-kms-provider
  namespace: kube-system
  labels:
    tier: control-plane
    app: vault-kms-provider
spec:
  selector:
    matchLabels:
      name: vault-kms-provider
  template:
    metadata:
      labels:
        name: vault-kms-provider
    spec:
      serviceAccountName: vault-auth
      priorityClassName: system-cluster-critical
      hostNetwork: true
      initContainers:
        - name: vault-agent
          image: vault
          securityContext:
            privileged: true
          args:
            - agent
            - -config=/etc/vault/vault-agent-config.hcl
            - -log-level=debug
          env:
            - name: VAULT_ADDR
              value: http://tdevhvc-01.trousseau.io:8200
          volumeMounts:
            - name: config
              mountPath: /etc/vault
            - name: shared-data 
              mountPath: /etc/secrets
      containers:
        - name: vault-kms-provider
          image: ghcr.io/ondat/trousseau:v1.1.0
          imagePullPolicy: Always
          env:                        
            #- name: VAULT_NAMESPACE    # For Enterprise - set the value for the namespace
            #  value: admin
            - name: VAULT_SKIP_VERIFY # For vault deployment with a self-signed certificate
              value: "true"           
          args:
            - -v=5
            - --config-file-path=/opt/trousseau/config.yaml
            - --listen-addr=unix:///opt/vault-kms/vaultkms.socket                            # [REQUIRED] Version of the key to use
            - --log-format-json=false
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: true
            runAsUser: 0
          ports:
            - containerPort: 8787
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8787
            failureThreshold: 3
            periodSeconds: 10
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 300m
              memory: 256Mi
          volumeMounts:
            - name: vault-kms
              mountPath: /opt/vault-kms
            - name: shared-data
              mountPath: /opt/trousseau/
      volumes:
        - name: vault-kms
          hostPath:
            path: /opt/vault-kms
        - configMap:
            items:
              - key: vault-agent-config.hcl
                path: vault-agent-config.hcl
            name: example-vault-agent-config
          name: config
        - emptyDir: {}
          name: shared-data
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/control-plane
                    operator: Exists
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
        - key: node-role.kubernetes.io/etcd
          operator: Exists
          effect: NoExecute
```
